# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a_star.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(900, 600)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton30.setObjectName("pushButton30")
        self.gridLayout.addWidget(self.pushButton30, 5, 0, 1, 1)
        self.pushButton21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton21.setObjectName("pushButton21")
        self.gridLayout.addWidget(self.pushButton21, 3, 3, 1, 1)
        self.pushButton19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton19.setObjectName("pushButton19")
        self.gridLayout.addWidget(self.pushButton19, 3, 1, 1, 1)
        self.pushButton15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton15.setObjectName("pushButton15")
        self.gridLayout.addWidget(self.pushButton15, 2, 3, 1, 1)
        self.pushButton24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton24.setObjectName("pushButton24")
        self.gridLayout.addWidget(self.pushButton24, 4, 0, 1, 1)
        self.pushButton9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton9.setObjectName("pushButton9")
        self.gridLayout.addWidget(self.pushButton9, 1, 3, 1, 1)
        self.pushButton27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton27.setObjectName("pushButton27")
        self.gridLayout.addWidget(self.pushButton27, 4, 3, 1, 1)
        self.pushButton22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton22.setObjectName("pushButton22")
        self.gridLayout.addWidget(self.pushButton22, 3, 4, 1, 1)
        self.pushButton6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton6.setObjectName("pushButton6")
        self.gridLayout.addWidget(self.pushButton6, 1, 0, 1, 1)
        self.pushButton10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton10.setObjectName("pushButton10")
        self.gridLayout.addWidget(self.pushButton10, 1, 4, 1, 1)
        self.pushButton16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton16.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton16.setObjectName("pushButton16")
        self.gridLayout.addWidget(self.pushButton16, 2, 4, 1, 1)
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setObjectName("pushButton1")
        self.gridLayout.addWidget(self.pushButton1, 0, 1, 1, 1)
        self.pushButton25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton25.setObjectName("pushButton25")
        self.gridLayout.addWidget(self.pushButton25, 4, 1, 1, 1)
        self.pushButton12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton12.setObjectName("pushButton12")
        self.gridLayout.addWidget(self.pushButton12, 2, 0, 1, 1)
        self.pushButton26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton26.setObjectName("pushButton26")
        self.gridLayout.addWidget(self.pushButton26, 4, 2, 1, 1)
        self.pushButton0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton0.setObjectName("pushButton0")
        self.gridLayout.addWidget(self.pushButton0, 0, 0, 1, 1)
        self.pushButton14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton14.setObjectName("pushButton14")
        self.gridLayout.addWidget(self.pushButton14, 2, 2, 1, 1)
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setObjectName("pushButton2")
        self.gridLayout.addWidget(self.pushButton2, 0, 2, 1, 1)
        self.pushButton7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton7.setObjectName("pushButton7")
        self.gridLayout.addWidget(self.pushButton7, 1, 1, 1, 1)
        self.pushButton8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton8.setObjectName("pushButton8")
        self.gridLayout.addWidget(self.pushButton8, 1, 2, 1, 1)
        self.pushButton18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton18.setObjectName("pushButton18")
        self.gridLayout.addWidget(self.pushButton18, 3, 0, 1, 1)
        self.pushButton13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton13.setObjectName("pushButton13")
        self.gridLayout.addWidget(self.pushButton13, 2, 1, 1, 1)
        self.pushButton20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton20.setObjectName("pushButton20")
        self.gridLayout.addWidget(self.pushButton20, 3, 2, 1, 1)
        self.pushButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton4.setObjectName("pushButton4")
        self.gridLayout.addWidget(self.pushButton4, 0, 4, 1, 1)
        self.pushButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton3.setObjectName("pushButton3")
        self.gridLayout.addWidget(self.pushButton3, 0, 3, 1, 1)
        self.pushButton28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton28.setObjectName("pushButton28")
        self.gridLayout.addWidget(self.pushButton28, 4, 4, 1, 1)
        self.pushButton5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton5.setObjectName("pushButton5")
        self.gridLayout.addWidget(self.pushButton5, 0, 5, 1, 1)
        self.pushButton31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton31.setObjectName("pushButton31")
        self.gridLayout.addWidget(self.pushButton31, 5, 1, 1, 1)
        self.pushButton11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton11.setObjectName("pushButton11")
        self.gridLayout.addWidget(self.pushButton11, 1, 5, 1, 1)
        self.pushButton32 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton32.setObjectName("pushButton32")
        self.gridLayout.addWidget(self.pushButton32, 5, 2, 1, 1)
        self.pushButton33 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton33.setObjectName("pushButton33")
        self.gridLayout.addWidget(self.pushButton33, 5, 3, 1, 1)
        self.pushButton17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton17.setObjectName("pushButton17")
        self.gridLayout.addWidget(self.pushButton17, 2, 5, 1, 1)
        self.pushButton34 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton34.setObjectName("pushButton34")
        self.gridLayout.addWidget(self.pushButton34, 5, 4, 1, 1)
        self.pushButton23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton23.setObjectName("pushButton23")
        self.gridLayout.addWidget(self.pushButton23, 3, 5, 1, 1)
        self.pushButton29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton29.setObjectName("pushButton29")
        self.gridLayout.addWidget(self.pushButton29, 4, 5, 1, 1)
        self.pushButton35 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton35.setObjectName("pushButton35")
        self.gridLayout.addWidget(self.pushButton35, 5, 5, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.gridLayout_run = QtWidgets.QGridLayout()
        self.gridLayout_run.setObjectName("gridLayout_run")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_run.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_run.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_run.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_run.addItem(spacerItem3, 14, 1, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.runButton.setFont(font)
        self.runButton.setObjectName("runButton")
        self.gridLayout_run.addWidget(self.runButton, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_run.addItem(spacerItem4, 1, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setObjectName("label_45")
        self.gridLayout_run.addWidget(self.label_45, 4, 2, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setObjectName("label_54")
        self.gridLayout_run.addWidget(self.label_54, 6, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setObjectName("label_47")
        self.gridLayout_run.addWidget(self.label_47, 11, 1, 1, 1)
        self.tile_info = QtWidgets.QLabel(self.centralwidget)
        self.tile_info.setObjectName("tile_info")
        self.gridLayout_run.addWidget(self.tile_info, 3, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setObjectName("label_39")
        self.gridLayout_run.addWidget(self.label_39, 7, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setObjectName("label_36")
        self.gridLayout_run.addWidget(self.label_36, 4, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setObjectName("label_38")
        self.gridLayout_run.addWidget(self.label_38, 6, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setObjectName("label_37")
        self.gridLayout_run.addWidget(self.label_37, 5, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setObjectName("label_46")
        self.gridLayout_run.addWidget(self.label_46, 5, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.gridLayout_run.addWidget(self.label_49, 10, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setObjectName("label_44")
        self.gridLayout_run.addWidget(self.label_44, 3, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setObjectName("label_48")
        self.gridLayout_run.addWidget(self.label_48, 12, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_run, 1, 2, 1, 1)
        self.gridLayout_utility = QtWidgets.QGridLayout()
        self.gridLayout_utility.setObjectName("gridLayout_utility")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setObjectName("label_41")
        self.gridLayout_utility.addWidget(self.label_41, 4, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setObjectName("label_40")
        self.gridLayout_utility.addWidget(self.label_40, 3, 1, 1, 1)
        self.set_water = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_water.sizePolicy().hasHeightForWidth())
        self.set_water.setSizePolicy(sizePolicy)
        self.set_water.setObjectName("set_water")
        self.gridLayout_utility.addWidget(self.set_water, 8, 3, 1, 1)
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setObjectName("label1")
        self.gridLayout_utility.addWidget(self.label1, 1, 1, 1, 1)
        self.set_road = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_road.sizePolicy().hasHeightForWidth())
        self.set_road.setSizePolicy(sizePolicy)
        self.set_road.setObjectName("set_road")
        self.gridLayout_utility.addWidget(self.set_road, 7, 1, 1, 1)
        self.set_mountain = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_mountain.sizePolicy().hasHeightForWidth())
        self.set_mountain.setSizePolicy(sizePolicy)
        self.set_mountain.setObjectName("set_mountain")
        self.gridLayout_utility.addWidget(self.set_mountain, 8, 1, 1, 1)
        self.set_grass = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_grass.sizePolicy().hasHeightForWidth())
        self.set_grass.setSizePolicy(sizePolicy)
        self.set_grass.setObjectName("set_grass")
        self.gridLayout_utility.addWidget(self.set_grass, 7, 3, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.gridLayout_utility.addWidget(self.label_42, 2, 1, 1, 1)
        self.roadlayout = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roadlayout.sizePolicy().hasHeightForWidth())
        self.roadlayout.setSizePolicy(sizePolicy)
        self.roadlayout.setObjectName("roadlayout")
        self.gridLayout_utility.addWidget(self.roadlayout, 11, 1, 1, 1)
        self.mountainlayout = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mountainlayout.sizePolicy().hasHeightForWidth())
        self.mountainlayout.setSizePolicy(sizePolicy)
        self.mountainlayout.setObjectName("mountainlayout")
        self.gridLayout_utility.addWidget(self.mountainlayout, 11, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_utility.addItem(spacerItem5, 12, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_utility.addItem(spacerItem6, 8, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_utility.addItem(spacerItem7, 11, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_utility.addItem(spacerItem8, 7, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_utility.addItem(spacerItem9, 6, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_utility.addItem(spacerItem10, 0, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_utility.addItem(spacerItem11, 9, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_utility.addItem(spacerItem12, 7, 4, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_utility.addItem(spacerItem13, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_utility.addWidget(self.label, 9, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setObjectName("label_50")
        self.gridLayout_utility.addWidget(self.label_50, 3, 3, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.centralwidget)
        self.label_52.setObjectName("label_52")
        self.gridLayout_utility.addWidget(self.label_52, 1, 3, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setObjectName("label_43")
        self.gridLayout_utility.addWidget(self.label_43, 10, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.centralwidget)
        self.label_53.setObjectName("label_53")
        self.gridLayout_utility.addWidget(self.label_53, 6, 3, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.centralwidget)
        self.label_51.setObjectName("label_51")
        self.gridLayout_utility.addWidget(self.label_51, 4, 3, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_utility.addItem(spacerItem14, 5, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_utility, 0, 1, 1, 1)
        self.gridLayout_display = QtWidgets.QGridLayout()
        self.gridLayout_display.setObjectName("gridLayout_display")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_display.addWidget(self.label_8, 3, 4, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setObjectName("label_29")
        self.gridLayout_display.addWidget(self.label_29, 6, 9, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setObjectName("label_31")
        self.gridLayout_display.addWidget(self.label_31, 7, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setObjectName("label_27")
        self.gridLayout_display.addWidget(self.label_27, 6, 6, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_display.addWidget(self.label_12, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_display.addWidget(self.label_11, 3, 9, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_display.addWidget(self.label_10, 3, 8, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setObjectName("label_28")
        self.gridLayout_display.addWidget(self.label_28, 6, 8, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_display.addWidget(self.label_9, 3, 6, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_display.addWidget(self.label_14, 4, 4, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setObjectName("label_33")
        self.gridLayout_display.addWidget(self.label_33, 7, 6, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setObjectName("label_35")
        self.gridLayout_display.addWidget(self.label_35, 7, 9, 1, 1)
        self.label_0 = QtWidgets.QLabel(self.centralwidget)
        self.label_0.setObjectName("label_0")
        self.gridLayout_display.addWidget(self.label_0, 2, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setObjectName("label_25")
        self.gridLayout_display.addWidget(self.label_25, 6, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_display.addWidget(self.label_15, 4, 6, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout_display.addWidget(self.label_21, 5, 6, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setObjectName("label_22")
        self.gridLayout_display.addWidget(self.label_22, 5, 8, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setObjectName("label_34")
        self.gridLayout_display.addWidget(self.label_34, 7, 8, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setObjectName("label_32")
        self.gridLayout_display.addWidget(self.label_32, 7, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout_display.addWidget(self.label_17, 4, 9, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setObjectName("label_30")
        self.gridLayout_display.addWidget(self.label_30, 7, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout_display.addWidget(self.label_20, 5, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout_display.addWidget(self.label_19, 5, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout_display.addWidget(self.label_18, 5, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout_display.addWidget(self.label_23, 5, 9, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_display.addWidget(self.label_5, 2, 9, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_display.addWidget(self.label_4, 2, 8, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_display.addWidget(self.label_3, 2, 6, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setObjectName("label_26")
        self.gridLayout_display.addWidget(self.label_26, 6, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setObjectName("label_24")
        self.gridLayout_display.addWidget(self.label_24, 6, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_display.addWidget(self.label_16, 4, 8, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_display.addWidget(self.label_2, 2, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_display.addWidget(self.label_7, 3, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_display.addWidget(self.label_13, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_display.addWidget(self.label_6, 3, 1, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setObjectName("label_1")
        self.gridLayout_display.addWidget(self.label_1, 2, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_display, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton30.setText(_translate("MainWindow", "PushButton"))
        self.pushButton21.setText(_translate("MainWindow", "PushButton"))
        self.pushButton19.setText(_translate("MainWindow", "PushButton"))
        self.pushButton15.setText(_translate("MainWindow", "PushButton"))
        self.pushButton24.setText(_translate("MainWindow", "PushButton"))
        self.pushButton9.setText(_translate("MainWindow", "PushButton"))
        self.pushButton27.setText(_translate("MainWindow", "PushButton"))
        self.pushButton22.setText(_translate("MainWindow", "PushButton"))
        self.pushButton6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton10.setText(_translate("MainWindow", "PushButton"))
        self.pushButton16.setText(_translate("MainWindow", "PushButton"))
        self.pushButton1.setText(_translate("MainWindow", "PushButton"))
        self.pushButton25.setText(_translate("MainWindow", "PushButton"))
        self.pushButton12.setText(_translate("MainWindow", "PushButton"))
        self.pushButton26.setText(_translate("MainWindow", "PushButton"))
        self.pushButton0.setText(_translate("MainWindow", "Print Message"))
        self.pushButton14.setText(_translate("MainWindow", "PushButton"))
        self.pushButton2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton7.setText(_translate("MainWindow", "PushButton"))
        self.pushButton8.setText(_translate("MainWindow", "PushButton"))
        self.pushButton18.setText(_translate("MainWindow", "PushButton"))
        self.pushButton13.setText(_translate("MainWindow", "PushButton"))
        self.pushButton20.setText(_translate("MainWindow", "PushButton"))
        self.pushButton4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton28.setText(_translate("MainWindow", "Print Message"))
        self.pushButton5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton31.setText(_translate("MainWindow", "PushButton"))
        self.pushButton11.setText(_translate("MainWindow", "PushButton"))
        self.pushButton32.setText(_translate("MainWindow", "PushButton"))
        self.pushButton33.setText(_translate("MainWindow", "PushButton"))
        self.pushButton17.setText(_translate("MainWindow", "PushButton"))
        self.pushButton34.setText(_translate("MainWindow", "PushButton"))
        self.pushButton23.setText(_translate("MainWindow", "PushButton"))
        self.pushButton29.setText(_translate("MainWindow", "PushButton"))
        self.pushButton35.setText(_translate("MainWindow", "PushButton"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.label_45.setText(_translate("MainWindow", "the shortest path in terms of cost"))
        self.label_54.setText(_translate("MainWindow", "and display it on the grid above"))
        self.label_47.setText(_translate("MainWindow", "There needs to exist exactly ONE"))
        self.tile_info.setText(_translate("MainWindow", "Each tile has a cost associated:"))
        self.label_39.setText(_translate("MainWindow", "Water : 100"))
        self.label_36.setText(_translate("MainWindow", "Roads : 1"))
        self.label_38.setText(_translate("MainWindow", "Mountain: 20"))
        self.label_37.setText(_translate("MainWindow", "Grass : 3"))
        self.label_46.setText(_translate("MainWindow", "from the start point and goal point"))
        self.label_44.setText(_translate("MainWindow", "Clicking the run command will find"))
        self.label_48.setText(_translate("MainWindow", "start point and goal point"))
        self.label_41.setText(_translate("MainWindow", "to the correspdoning tile"))
        self.label_40.setText(_translate("MainWindow", "These buttons set the entire map "))
        self.set_water.setText(_translate("MainWindow", "Set Water"))
        self.label1.setText(_translate("MainWindow", "Modify the map:"))
        self.set_road.setText(_translate("MainWindow", "Set Road"))
        self.set_mountain.setText(_translate("MainWindow", "Set Mountain"))
        self.set_grass.setText(_translate("MainWindow", "Set Grass"))
        self.roadlayout.setText(_translate("MainWindow", "Road Layout"))
        self.mountainlayout.setText(_translate("MainWindow", "Mountain Layout"))
        self.label.setText(_translate("MainWindow", "Presets"))
        self.label_50.setText(_translate("MainWindow", "You can cycle between tiles with"))
        self.label_52.setText(_translate("MainWindow", "Controls:"))
        self.label_43.setText(_translate("MainWindow", "Sample layouts for you to select"))
        self.label_53.setText(_translate("MainWindow", "Tile Order \n"
" Start>Road>Grass>Mountain>Water>Goal"))
        self.label_51.setText(_translate("MainWindow", "left click and right click"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_29.setText(_translate("MainWindow", "TextLabel"))
        self.label_31.setText(_translate("MainWindow", "TextLabel"))
        self.label_27.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_28.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_33.setText(_translate("MainWindow", "TextLabel"))
        self.label_35.setText(_translate("MainWindow", "TextLabel"))
        self.label_0.setText(_translate("MainWindow", "label1"))
        self.label_25.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_21.setText(_translate("MainWindow", "TextLabel"))
        self.label_22.setText(_translate("MainWindow", "TextLabel"))
        self.label_34.setText(_translate("MainWindow", "TextLabel"))
        self.label_32.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.label_30.setText(_translate("MainWindow", "TextLabel"))
        self.label_20.setText(_translate("MainWindow", "TextLabel"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.label_23.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_26.setText(_translate("MainWindow", "TextLabel"))
        self.label_24.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "label3"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_1.setText(_translate("MainWindow", "label2"))

import imgs_rc
